export interface DiscoveryFilterOption {
  key: string;
  label: string;
  type: "select" | "multiselect" | "range" | "toggle" | "text";
  options?: string[];
}

export interface DiscoveryCategory {
  key: string;
  emoji: string;
  label: string;
}

export interface DiscoveryTripType {
  key: string;
  emoji: string;
  label: string;
  /** האם עיר היא שדה חובה עבור סוג הטיול הזה (טבע/חו"ל - לא בהכרח). */
  cityRequired: boolean;
  categories: DiscoveryCategory[];
  /** שכבה שנייה, ספציפית יותר, שמופיעה **אחרי** בחירת הקטגוריה הראשית -
   *  כרגע רלוונטי לחופשה בחו"ל בלבד (סגנון חופשה כללי -> מה ספציפית
   *  לחפש ביעד, אותה רשימה כמו טיול יומי + "אתרי חובה ביעד"). */
  secondaryCategories?: DiscoveryCategory[];
  filters: DiscoveryFilterOption[];
}

/** בדיוק אותן 20 קטגוריות כמו טיול יומי, פלוס "אתרי חובה ביעד" - נשלף
 *  לשימוש חוזר עבור חו"ל, כדי לא לשכפל את הרשימה בטעות עם הבדלים קטנים. */
const DETAILED_ATTRACTION_CATEGORIES: DiscoveryCategory[] = [
  { key: "coffee_carts", emoji: "☕", label: "עגלות קפה ובתי קפה" },
  { key: "nature_trails", emoji: "🌿", label: "מסלולי טבע ונופים" },
  { key: "beaches_pools", emoji: "🏖️", label: "חופי ים, אגמים ובריכות" },
  { key: "viewpoints", emoji: "🌅", label: "תצפיות, זריחות ושקיעות" },
  { key: "parks_picnic", emoji: "🌳", label: "פארקים, גנים ופינות פיקניק" },
  { key: "water_parks", emoji: "🎡", label: "פארקי מים, שעשועים ומתקנים" },
  { key: "attractions", emoji: "🎯", label: "אטרקציות ופעילויות" },
  { key: "sports_extreme", emoji: "🚴", label: "ספורט ואקסטרים" },
  { key: "restaurants", emoji: "🍽️", label: "מסעדות וקולינריה" },
  { key: "wineries", emoji: "🍷", label: "יקבים ומבשלות" },
  { key: "culture_museums", emoji: "🏛️", label: "תרבות, מוזיאונים והיסטוריה" },
  { key: "shopping", emoji: "🛍️", label: "שופינג, קניות ושווקים" },
  { key: "events", emoji: "🎪", label: "אירועים, הופעות ופסטיבלים" },
  { key: "nightlife", emoji: "🎭", label: "חיי לילה ובילויים" },
  { key: "spa", emoji: "🧖", label: "ספא, מרחצאות ורוגע" },
  { key: "boating", emoji: "🛶", label: "שיט ואטרקציות מים" },
  { key: "heritage", emoji: "🛕", label: "אתרי מורשת ומקומות קדושים" },
  { key: "kids_family", emoji: "👨‍👩‍👧‍👦", label: "פעילויות לילדים ומשפחות" },
  { key: "art_galleries", emoji: "🎨", label: "אמנות וגלריות" },
  { key: "photo_spots", emoji: "📸", label: "נקודות צילום ואינסטגרם" },
  { key: "must_see_landmarks", emoji: "🗽", label: "אתרי חובה ביעד" },
];

/** מקור: המפרט ה-MASTER המלא (102 סעיפים) - סעיפים 10-28. תוכן מדויק,
 *  לא מפושט/מנוחש. כל סוג טיול מציג רק את הקטגוריות/פילטרים שלו -
 *  "אין להציג פילטרים שאינם רלוונטיים" (סעיף 86-87). */
export const DISCOVERY_TRIP_TYPES: DiscoveryTripType[] = [
  {
    key: "day_trip",
    emoji: "☀️",
    label: "טיול יומי",
    cityRequired: true,
    categories: [
      { key: "coffee_carts", emoji: "☕", label: "עגלות קפה ובתי קפה" },
      { key: "nature_trails", emoji: "🌿", label: "מסלולי טבע ונופים" },
      { key: "beaches_pools", emoji: "🏖️", label: "חופי ים, אגמים ובריכות" },
      { key: "viewpoints", emoji: "🌅", label: "תצפיות, זריחות ושקיעות" },
      { key: "parks_picnic", emoji: "🌳", label: "פארקים, גנים ופינות פיקניק" },
      { key: "water_parks", emoji: "🎡", label: "פארקי מים, שעשועים ומתקנים" },
      { key: "attractions", emoji: "🎯", label: "אטרקציות ופעילויות" },
      { key: "sports_extreme", emoji: "🚴", label: "ספורט ואקסטרים" },
      { key: "restaurants", emoji: "🍽️", label: "מסעדות וקולינריה" },
      { key: "wineries", emoji: "🍷", label: "יקבים ומבשלות" },
      { key: "culture_museums", emoji: "🏛️", label: "תרבות, מוזיאונים והיסטוריה" },
      { key: "shopping", emoji: "🛍️", label: "שופינג, קניות ושווקים" },
      { key: "events", emoji: "🎪", label: "אירועים, הופעות ופסטיבלים" },
      { key: "nightlife", emoji: "🎭", label: "חיי לילה ובילויים" },
      { key: "spa", emoji: "🧖", label: "ספא, מרחצאות ורוגע" },
      { key: "boating", emoji: "🛶", label: "שיט ואטרקציות מים" },
      { key: "heritage", emoji: "🛕", label: "אתרי מורשת ומקומות קדושים" },
      { key: "kids_family", emoji: "👨‍👩‍👧‍👦", label: "פעילויות לילדים ומשפחות" },
      { key: "art_galleries", emoji: "🎨", label: "אמנות וגלריות" },
      { key: "photo_spots", emoji: "📸", label: "נקודות צילום ואינסטגרם" },
    ],
    filters: [
      { key: "country", label: "מדינה", type: "text" },
      { key: "city", label: "עיר / יעד", type: "text" },
      { key: "area", label: "אזור", type: "text" },
      { key: "date", label: "תאריך", type: "text" },
      { key: "visit_time", label: "שעת ביקור", type: "text" },
      { key: "budget", label: "תקציב", type: "range" },
      { key: "ages", label: "גילאים", type: "text" },
      { key: "companions", label: "הרכב", type: "select", options: ["זוג", "משפחה", "חברים", "יחיד"] },
      { key: "accessibility", label: "נגישות", type: "toggle" },
      { key: "mobility", label: "התניידות", type: "select", options: ["רכב פרטי", "תחבורה ציבורית", "הליכה"] },
      { key: "weather", label: "מזג אוויר", type: "select", options: ["חם", "קר", "גשום", "לא משנה"] },
      { key: "indoor_outdoor", label: "Indoor / Outdoor", type: "select", options: ["Indoor", "Outdoor", "שניהם"] },
      { key: "duration", label: "משך ביקור", type: "text" },
      { key: "max_distance", label: "מרחק מקסימלי", type: "range" },
      { key: "min_rating", label: "דירוג Google מינימלי", type: "range" },
      { key: "min_reviews", label: "מספר ביקורות מינימלי", type: "range" },
      { key: "season", label: "עונת השנה", type: "select", options: ["אביב", "קיץ", "סתיו", "חורף"] },
      { key: "difficulty", label: "רמת קושי", type: "select", options: ["קל", "בינוני", "מאתגר"] },
      { key: "quantity", label: "כמות מקומות רצויה", type: "range" },
    ],
  },
  {
    key: "nature_trip",
    emoji: "🌿",
    label: "טיול בטבע",
    cityRequired: false,
    categories: [
      { key: "springs", emoji: "💧", label: "מעיינות ונחלים" },
      { key: "viewpoints", emoji: "🌄", label: "תצפיות ונופים" },
      { key: "forests", emoji: "🌳", label: "יערות וחורשות" },
      { key: "hiking_trails", emoji: "🥾", label: "מסלולי הליכה" },
      { key: "seasonal_bloom", emoji: "🌸", label: "פריחה עונתית" },
      { key: "caves", emoji: "🪨", label: "מערות ותופעות טבע" },
      { key: "desert_canyons", emoji: "🏜️", label: "מדבר וקניונים" },
      { key: "waterfalls", emoji: "💦", label: "מפלים" },
      { key: "wildlife", emoji: "🦌", label: "טבע ובעלי חיים" },
      { key: "sunrise_sunset", emoji: "🌅", label: "זריחה או שקיעה" },
      { key: "photo_spots", emoji: "📸", label: "מקומות פוטוגניים" },
      { key: "picnic", emoji: "🧺", label: "פיקניק בטבע" },
      { key: "nature_reserves", emoji: "🌿", label: "שמורות טבע" },
    ],
    filters: [
      { key: "country", label: "מדינה", type: "text" },
      { key: "region", label: "אזור בארץ", type: "text" },
      { key: "date", label: "תאריך", type: "text" },
      { key: "season", label: "עונה", type: "select", options: ["אביב", "קיץ", "סתיו", "חורף"] },
      { key: "difficulty", label: "רמת קושי", type: "select", options: ["🟢 קל", "🟠 בינוני", "🔴 מאתגר"] },
      { key: "trail_length", label: "אורך מסלול", type: "text" },
      { key: "trail_time", label: "זמן מסלול", type: "text" },
      { key: "max_distance", label: "מרחק", type: "range" },
      { key: "elevation_gain", label: "הפרש גובה", type: "text" },
      { key: "water", label: "מעיינות / מים", type: "toggle" },
      { key: "kids_friendly", label: "מתאים לילדים", type: "toggle" },
      { key: "stroller_friendly", label: "מתאים לעגלות", type: "toggle" },
      { key: "pets", label: "חיות מחמד", type: "toggle" },
      { key: "accessibility", label: "נגישות", type: "toggle" },
      { key: "weather", label: "מזג אוויר", type: "select", options: ["חם", "קר", "גשום", "לא משנה"] },
      { key: "indoor_outdoor", label: "Indoor / Outdoor", type: "select", options: ["Indoor", "Outdoor"] },
      { key: "sunrise_sunset", label: "זריחה / שקיעה", type: "toggle" },
      { key: "budget", label: "תקציב", type: "range" },
      { key: "min_rating", label: "דירוג Google", type: "range" },
      { key: "min_reviews", label: "מספר ביקורות", type: "range" },
      { key: "quantity", label: "כמות מקומות רצויה", type: "range" },
    ],
  },
  {
    key: "weekend",
    emoji: "🏨",
    label: "סופ\"ש",
    cityRequired: true,
    categories: [
      { key: "beach_relax", emoji: "🏖️", label: "בטן גב וחופים" },
      { key: "family", emoji: "👨‍👩‍👧‍👦", label: "חופשה משפחתית" },
      { key: "seasonal", emoji: "🎄", label: "חופשות עונתיות" },
      { key: "romantic", emoji: "💑", label: "חופשה רומנטית וירח דבש" },
      { key: "live_shows", emoji: "🎤", label: "הופעות חיות ופסטיבלים" },
      { key: "luxury", emoji: "💎", label: "יוקרה ופינוקים" },
      { key: "spa_wellness", emoji: "🧖", label: "ספא, וולנס וריטריטים" },
      { key: "sports_events", emoji: "🏟️", label: "אירועי ספורט" },
      { key: "backpacking", emoji: "🎒", label: "טיולי תרמילאים" },
      { key: "urban", emoji: "🏙️", label: "חופשה עירונית" },
      { key: "nightlife", emoji: "🌃", label: "מסיבות וחיי לילה" },
    ],
    filters: [
      { key: "country", label: "מדינה", type: "text" },
      { key: "city", label: "עיר / יעד", type: "text" },
      { key: "area", label: "אזור", type: "text" },
      { key: "dates", label: "תאריכים", type: "text" },
      { key: "nights", label: "מספר לילות", type: "range" },
      { key: "total_budget", label: "תקציב כולל", type: "range" },
      { key: "budget_per_night", label: "תקציב ללילה", type: "range" },
      { key: "companions", label: "הרכב", type: "select", options: ["זוג", "משפחה", "חברים", "יחיד"] },
      { key: "child_ages", label: "גילאי ילדים", type: "text" },
      { key: "lodging_type", label: "סוג לינה", type: "select", options: ["מלון", "ריזורט", "דירה", "צימר", "הוסטל", "קמפינג", "גלמפינג", "וילה"] },
      { key: "style", label: "סגנון חופשה", type: "text" },
      { key: "pace", label: "קצב", type: "select", options: ["🌿 רגוע", "⚖️ מאוזן", "🚀 מתוכנן"] },
      { key: "accessibility", label: "נגישות", type: "toggle" },
      { key: "interests", label: "תחומי עניין", type: "multiselect" },
      { key: "quantity", label: "מספר מקומות רצוי", type: "range" },
      { key: "min_rating", label: "דירוג Google", type: "range" },
      { key: "min_reviews", label: "מספר ביקורות", type: "range" },
    ],
  },
  {
    key: "romantic_date",
    emoji: "💕",
    label: "דייט רומנטי",
    cityRequired: true,
    categories: [
      { key: "partner", emoji: "💑", label: "בן/בת זוג" },
      { key: "first_date", emoji: "✨", label: "דייט ראשון" },
      { key: "few_dates", emoji: "😊", label: "כמה דייטים" },
      { key: "anniversary", emoji: "💍", label: "יום נישואין" },
      { key: "proposal", emoji: "💎", label: "הצעת נישואין" },
      { key: "special_event", emoji: "🎉", label: "אירוע מיוחד" },
      { key: "romantic_meal", emoji: "🍽️", label: "ארוחה רומנטית" },
      { key: "sunset_view", emoji: "🌅", label: "שקיעה ונוף" },
      { key: "beach", emoji: "🏖️", label: "חוף ים" },
      { key: "winery_bar", emoji: "🍷", label: "יקב או בר יין" },
      { key: "cafe", emoji: "☕", label: "בית קפה" },
      { key: "culture_show", emoji: "🎭", label: "תרבות והופעה" },
      { key: "couples_workshop", emoji: "🎨", label: "סדנה זוגית" },
      { key: "spa", emoji: "🧖", label: "ספא" },
      { key: "nightlife", emoji: "🌃", label: "בילוי לילי" },
    ],
    filters: [
      { key: "country", label: "מדינה", type: "text" },
      { key: "city", label: "עיר", type: "text" },
      { key: "area", label: "אזור", type: "text" },
      { key: "date", label: "תאריך", type: "text" },
      { key: "time", label: "שעה", type: "text" },
      { key: "budget", label: "תקציב", type: "range" },
      { key: "romance_level", label: "רמת רומנטיות", type: "range" },
      { key: "sunset", label: "שקיעה", type: "toggle" },
      { key: "indoor_outdoor", label: "Indoor / Outdoor", type: "select", options: ["Indoor", "Outdoor"] },
      { key: "atmosphere", label: "אווירה", type: "text" },
      { key: "luxury", label: "יוקרה", type: "toggle" },
      { key: "quiet", label: "שקט", type: "toggle" },
      { key: "parking", label: "חניה", type: "toggle" },
      { key: "accessibility", label: "נגישות", type: "toggle" },
      { key: "transportation", label: "תחבורה", type: "text" },
      { key: "min_rating", label: "דירוג Google", type: "range" },
      { key: "min_reviews", label: "מספר ביקורות", type: "range" },
      { key: "quantity", label: "כמות מקומות רצויה", type: "range" },
    ],
  },
  {
    key: "restaurants_cafes",
    emoji: "🍽️",
    label: "מסעדות ובתי קפה",
    cityRequired: true,
    categories: [
      { key: "israeli", emoji: "🥙", label: "ישראלי" },
      { key: "italian", emoji: "🍝", label: "איטלקי" },
      { key: "asian", emoji: "🥢", label: "אסייתי" },
      { key: "bbq", emoji: "🍖", label: "בשרים ועל האש" },
      { key: "burger_diner", emoji: "🍔", label: "המבורגר ודיינר" },
      { key: "mexican", emoji: "🌮", label: "מקסיקני" },
      { key: "greek", emoji: "🫓", label: "יווני" },
      { key: "french_bistro", emoji: "🥖", label: "ביסטרו צרפתי" },
      { key: "indian", emoji: "🍛", label: "הודי" },
      { key: "mediterranean", emoji: "🫒", label: "ים-תיכוני" },
      { key: "seafood", emoji: "🐟", label: "דגים ופירות ים" },
      { key: "pizza", emoji: "🍕", label: "פיצה" },
      { key: "brunch", emoji: "🥐", label: "בראנץ'" },
      { key: "cafe", emoji: "☕", label: "בית קפה" },
      { key: "desserts", emoji: "🍰", label: "מתוקים" },
    ],
    filters: [
      { key: "country", label: "מדינה", type: "text" },
      { key: "city", label: "עיר", type: "text" },
      { key: "area", label: "אזור", type: "text" },
      { key: "kosher", label: "כשר", type: "toggle" },
      { key: "vegetarian", label: "צמחוני", type: "toggle" },
      { key: "vegan", label: "טבעוני", type: "toggle" },
      { key: "accessibility", label: "נגישות", type: "toggle" },
      { key: "budget", label: "תקציב", type: "range" },
      { key: "price_level", label: "רמת מחיר", type: "select", options: ["₪", "₪₪", "₪₪₪", "₪₪₪₪"] },
      { key: "visit_time", label: "שעת ביקור", type: "select", options: ["ארוחת בוקר", "בראנץ'", "צהריים", "ערב", "לילה"] },
      { key: "romantic", label: "רומנטי", type: "toggle" },
      { key: "family_friendly", label: "משפחתי", type: "toggle" },
      { key: "outdoor_seating", label: "ישיבה בחוץ", type: "toggle" },
      { key: "parking", label: "חניה", type: "toggle" },
      { key: "min_rating", label: "דירוג Google", type: "range" },
      { key: "min_reviews", label: "מספר ביקורות", type: "range" },
      { key: "quantity", label: "כמות מסעדות רצויה", type: "range" },
    ],
  },
  {
    key: "nightlife",
    emoji: "🌃",
    label: "חיי לילה",
    cityRequired: true,
    categories: [
      { key: "cocktail_bar", emoji: "🍸", label: "בר קוקטיילים" },
      { key: "wine_bar", emoji: "🍷", label: "בר יין" },
      { key: "club", emoji: "🎧", label: "מועדון" },
      { key: "live_show", emoji: "🎤", label: "הופעה חיה" },
      { key: "standup", emoji: "🎭", label: "סטנדאפ" },
      { key: "theater", emoji: "🎙️", label: "תיאטרון" },
      { key: "karaoke", emoji: "🎳", label: "קריוקי" },
      { key: "bowling", emoji: "🎳", label: "באולינג" },
      { key: "snooker", emoji: "🎱", label: "סנוקר" },
      { key: "arcade", emoji: "🕹️", label: "ארקייד" },
    ],
    filters: [
      { key: "country", label: "מדינה", type: "text" },
      { key: "city", label: "עיר", type: "text" },
      { key: "area", label: "אזור", type: "text" },
      { key: "date", label: "תאריך", type: "text" },
      { key: "time", label: "שעה", type: "text" },
      { key: "companions", label: "הרכב", type: "select", options: ["💑 זוג", "👥 חברים", "👦‍👧‍👩‍👨 קבוצה", "🙋 לבד"] },
      { key: "group_size", label: "גודל קבוצה", type: "select", options: ["5-10", "10-20", "20+"] },
      { key: "min_age", label: "גיל מינימום", type: "range" },
      { key: "budget", label: "תקציב", type: "range" },
      { key: "reservation_required", label: "הזמנה מראש", type: "toggle" },
      { key: "entry_fee", label: "דמי כניסה", type: "toggle" },
      { key: "dress_code", label: "קוד לבוש", type: "toggle" },
      { key: "noise_level", label: "רמת רעש", type: "text" },
      { key: "seating", label: "ישיבה", type: "toggle" },
      { key: "dancing", label: "ריקודים", type: "toggle" },
      { key: "accessibility", label: "נגישות", type: "toggle" },
      { key: "transportation", label: "תחבורה", type: "text" },
      { key: "parking", label: "חניה", type: "toggle" },
      { key: "min_rating", label: "דירוג Google", type: "range" },
      { key: "min_reviews", label: "מספר ביקורות", type: "range" },
      { key: "quantity", label: "כמות מקומות רצויה", type: "range" },
    ],
  },
  {
    key: "abroad_vacation",
    emoji: "✈️",
    label: "חופשה בחו\"ל",
    cityRequired: true,
    secondaryCategories: DETAILED_ATTRACTION_CATEGORIES,
    categories: [
      { key: "beach_relax", emoji: "🏖️", label: "בטן גב וחופים" },
      { key: "casino", emoji: "🎰", label: "קזינו והימורים" },
      { key: "cruise", emoji: "🛳️", label: "קרוזים ושייט" },
      { key: "family", emoji: "👨‍👩‍👧‍👦", label: "חופשה משפחתית" },
      { key: "seasonal", emoji: "🎄", label: "חופשות עונתיות" },
      { key: "romantic", emoji: "💑", label: "חופשה רומנטית וירח דבש" },
      { key: "live_shows", emoji: "🎤", label: "הופעות חיות ופסטיבלים" },
      { key: "digital_nomad", emoji: "💻", label: "נוודות דיגיטלית" },
      { key: "luxury", emoji: "💎", label: "יוקרה ופינוקים" },
      { key: "spa_wellness", emoji: "🧖", label: "ספא, וולנס וריטריטים" },
      { key: "ski", emoji: "⛷️", label: "סקי וספורט חורף" },
      { key: "sports_events", emoji: "🏟️", label: "אירועי ספורט" },
      { key: "backpacking", emoji: "🎒", label: "טיולי תרמילאים" },
      { key: "tropical", emoji: "🌴", label: "חופשות טרופיות" },
      { key: "urban", emoji: "🏙️", label: "חופשה עירונית" },
      { key: "nightlife", emoji: "🌃", label: "מסיבות וחיי לילה" },
    ],
    filters: [
      { key: "companions", label: "הרכב", type: "select", options: ["זוג", "משפחה", "חברים", "יחיד"] },
      { key: "child_ages", label: "גילאי ילדים", type: "text" },
      { key: "country", label: "מדינה", type: "text" },
      { key: "city", label: "עיר / יעד", type: "text" },
      { key: "budget", label: "תקציב", type: "range" },
      { key: "lodging_type", label: "סוג לינה", type: "select", options: ["🏨 מלון", "🏝️ ריזורט", "🏠 דירה", "🛖 צימר", "🛏️ הוסטל", "⛺ קמפינג", "🏕️ גלמפינג", "🏡 וילה"] },
      { key: "style", label: "סגנון חופשה", type: "text" },
      { key: "pace", label: "קצב", type: "select", options: ["🌿 רגוע", "⚖️ מאוזן", "🚀 מתוכנן"] },
      { key: "flight", label: "טיסה", type: "select", options: ["🎯 ישירה", "🔄 קונקשן אחד", "🔁 שניים ומעלה"] },
      { key: "travel_style", label: "סגנון נסיעה", type: "select", options: ["יעד אחד", "מספר יעדים"] },
      { key: "season", label: "עונה", type: "select", options: ["אביב", "קיץ", "סתיו", "חורף"] },
      { key: "min_rating", label: "דירוג", type: "range" },
      { key: "accessibility", label: "נגישות", type: "toggle" },
      { key: "quantity", label: "כמות יעדים / מקומות", type: "range" },
    ],
  },
];
