export interface TaxonomyOption {
  id: string;
  label: string;
}

export interface TripTypeGroup {
  id: string;
  label: string;
  emoji: string;
  subTags: TaxonomyOption[];
}

/** 12 סוגי הטיול הראשיים, כל אחד עם תתי-תגיות לבחירה מרובה. */
export const TRIP_TYPE_GROUPS: TripTypeGroup[] = [
  {
    id: "coffee_carts_cafes",
    label: "עגלות קפה ובתי קפה",
    emoji: "☕",
    subTags: [
      { id: "cafe", label: "בתי קפה" },
      { id: "coffee_cart", label: "עגלות קפה" },
      { id: "specialty_coffee", label: "קפה מיוחד/בוטיק" },
      { id: "cafe_with_view", label: "בית קפה עם נוף" },
      { id: "dog_friendly_cafe", label: "בית קפה ידידותי לכלבים" },
      { id: "bakery_cafe", label: "מאפייה עם ישיבה" },
    ],
  },
  {
    id: "nature_trails",    label: "מסלולי טבע ונופים",
    emoji: "🌿",
    subTags: [
      { id: "nature_reserve", label: "שמורות טבע" },
      { id: "hiking_trail", label: "מסלולי הליכה" },
      { id: "trip_route", label: "מסלולי טיול" },
      { id: "forest", label: "יערות" },
      { id: "grove", label: "חורשות" },
      { id: "mountain", label: "הרים" },
      { id: "canyon", label: "קניונים" },
      { id: "valley", label: "עמקים" },
      { id: "hill", label: "גבעות" },
      { id: "seasonal_bloom", label: "פריחות עונתיות" },
      { id: "natural_cave", label: "מערות טבע" },
      { id: "hanging_bridge", label: "גשרים תלויים" },
      { id: "accessible_trail", label: "מסלולים נגישים" },
      { id: "special_nature_site", label: "אתרי טבע מיוחדים" },
    ],
  },
  {
    id: "beaches_pools",
    label: "חופי ים ובריכות",
    emoji: "🏖️",
    subTags: [
      { id: "sea_beach", label: "חופי ים" },
      { id: "kinneret_beach", label: "חופי כנרת" },
      { id: "lake", label: "אגמים" },
      { id: "natural_pool", label: "בריכות טבעיות" },
      { id: "wading_pool", label: "בריכות שכשוך" },
      { id: "lagoon", label: "לגונות" },
      { id: "organized_beach", label: "חופים מוסדרים" },
      { id: "wild_beach", label: "חופים פראיים" },
      { id: "swimming_pool", label: "בריכות שחייה" },
      { id: "infinity_pool", label: "בריכות אינפיניטי" },
      { id: "family_beach", label: "חופי רחצה למשפחות" },
    ],
  },
  {
    id: "viewpoints",
    label: "תצפיות, זריחות ושקיעות",
    emoji: "🌅",
    subTags: [
      { id: "viewpoint", label: "נקודות תצפית" },
      { id: "view_balcony", label: "מרפסות נוף" },
      { id: "lookout", label: "מצפורים" },
      { id: "mountain_view", label: "תצפיות הרים" },
      { id: "city_view", label: "תצפיות עירוניות" },
      { id: "sunrise_point", label: "נקודות זריחה" },
      { id: "sunset_point", label: "נקודות שקיעה" },
      { id: "night_view", label: "תצפיות לילה" },
      { id: "stargazing", label: "תצפיות כוכבים" },
      { id: "photo_spot", label: "נקודות צילום מיוחדות" },
    ],
  },
  {
    id: "parks_gardens",
    label: "פארקים וגנים",
    emoji: "🌳",
    subTags: [
      { id: "urban_park", label: "פארקים עירוניים" },
      { id: "national_park", label: "פארקים לאומיים" },
      { id: "botanical_garden", label: "גנים בוטניים" },
      { id: "flower_park", label: "פארקי פרחים" },
      { id: "sculpture_garden", label: "גני פסלים" },
      { id: "nature_park", label: "פארקי טבע" },
      { id: "picnic_park", label: "פארקי פיקניק" },
      { id: "public_garden", label: "גנים ציבוריים" },
      { id: "playground_complex", label: "מתחמי משחק לילדים" },
    ],
  },
  {
    id: "water_amusement_parks",
    label: "פארקי מים, שעשועים ומתקנים",
    emoji: "🎡",
    subTags: [
      { id: "water_park", label: "פארקי מים" },
      { id: "amusement_park", label: "לונה פארקים" },
      { id: "entertainment_park", label: "פארקי שעשועים" },
      { id: "trampoline_park", label: "פארקי טרמפולינות" },
      { id: "rope_park", label: "פארקי חבלים" },
      { id: "snow_park", label: "פארקי שלג" },
      { id: "adventure_park", label: "פארקי אתגר" },
      { id: "zipline", label: "אומגות" },
      { id: "climbing_wall", label: "קירות טיפוס" },
      { id: "extreme_facility", label: "מתקני אקסטרים" },
      { id: "big_play_area", label: "מתחמי משחק גדולים" },
    ],
  },
  {
    id: "attractions_activities",
    label: "אטרקציות ופעילויות",
    emoji: "🎯",
    subTags: [
      { id: "escape_room", label: "חדרי בריחה" },
      { id: "vr_venue", label: "מתחמי VR" },
      { id: "illusion_museum", label: "מוזיאוני אשליות" },
      { id: "workshop", label: "סדנאות" },
      { id: "self_picking_farm", label: "קטיף עצמי" },
      { id: "visitor_farm", label: "חוות מבקרים" },
      { id: "petting_zoo", label: "פינות ליטוף" },
      { id: "zoo", label: "גני חיות" },
      { id: "safari", label: "ספארי" },
      { id: "aquarium", label: "אקווריומים" },
      { id: "visitor_center", label: "מרכזי מבקרים" },
      { id: "cable_car", label: "רכבלים" },
      { id: "tourist_train", label: "רכבות תיירותיות" },
      { id: "guided_tour", label: "סיורים מודרכים" },
      { id: "family_activity", label: "פעילויות לכל המשפחה" },
    ],
  },
  {
    id: "sports_extreme",
    label: "ספורט ואקסטרים",
    emoji: "🚴",
    subTags: [
      { id: "cycling", label: "רכיבת אופניים" },
      { id: "mountain_biking", label: "אופני שטח" },
      { id: "atv", label: "טרקטורונים" },
      { id: "raiser", label: "רייזרים" },
      { id: "jeep_tour", label: "ג'יפים" },
      { id: "horseback_riding", label: "רכיבת סוסים" },
      { id: "kayaking", label: "קיאקים" },
      { id: "sup", label: "סאפ" },
      { id: "surfing", label: "גלישת גלים" },
      { id: "windsurfing", label: "גלישת רוח" },
      { id: "diving", label: "צלילה" },
      { id: "snorkeling", label: "שנורקל" },
      { id: "climbing", label: "טיפוס" },
      { id: "bungee", label: "בנג'י" },
      { id: "paragliding", label: "מצנחי רחיפה" },
      { id: "water_skiing", label: "סקי מים" },
      { id: "wakeboarding", label: "וויקבורד" },
    ],
  },
  {
    id: "wineries_dining",
    label: "יקבים, מבשלות ומסעדות",
    emoji: "🍷",
    subTags: [
      { id: "winery", label: "יקבים" },
      { id: "brewery", label: "מבשלות בירה" },
      { id: "distillery", label: "מזקקות" },
      { id: "chef_restaurant", label: "מסעדות שף" },
      { id: "local_restaurant", label: "מסעדות מקומיות" },
      { id: "bakery", label: "מאפיות" },
      { id: "patisserie", label: "קונדיטוריות" },
      { id: "ice_cream_shop", label: "גלידריות" },
      { id: "food_market", label: "שווקי אוכל" },
      { id: "food_complex", label: "מתחמי אוכל" },
      { id: "wine_tasting", label: "טעימות יין" },
      { id: "beer_tasting", label: "טעימות בירה" },
      { id: "culinary_tour", label: "סיורים קולינריים" },
    ],
  },
  {
    id: "culture_history",
    label: "תרבות, מוזיאונים והיסטוריה",
    emoji: "🏛️",
    subTags: [
      { id: "museum", label: "מוזיאונים" },
      { id: "heritage_site", label: "אתרי מורשת" },
      { id: "archaeological_site", label: "אתרים ארכאולוגיים" },
      { id: "fortress", label: "מבצרים" },
      { id: "citadel", label: "מצודות" },
      { id: "historic_building", label: "מבנים היסטוריים" },
      { id: "church", label: "כנסיות" },
      { id: "monastery", label: "מנזרים" },
      { id: "ancient_synagogue", label: "בתי כנסת עתיקים" },
      { id: "mosque", label: "מסגדים" },
      { id: "gallery", label: "גלריות" },
      { id: "exhibition", label: "תערוכות" },
      { id: "culture_center", label: "מרכזי תרבות" },
      { id: "artists_village", label: "כפרי אמנים" },
      { id: "historic_street", label: "רחובות היסטוריים" },
    ],
  },
  {
    id: "shopping",
    label: "שופינג, קניות ושווקים",
    emoji: "🛍️",
    subTags: [
      { id: "mall", label: "קניונים" },
      { id: "shopping_center", label: "מרכזי קניות" },
      { id: "outlet", label: "אאוטלטים" },
      { id: "market", label: "שווקים" },
      { id: "food_market_shopping", label: "שוקי אוכל" },
      { id: "flea_market", label: "שוקי פשפשים" },
      { id: "artisan_fair", label: "ירידי אומנים" },
      { id: "boutique", label: "חנויות בוטיק" },
      { id: "open_shopping_area", label: "מתחמי קניות פתוחים" },
      { id: "local_shop", label: "חנויות מקומיות" },
    ],
  },
  {
    id: "events_festivals",
    label: "אירועים ופסטיבלים",
    emoji: "🎪",
    subTags: [
      { id: "festival", label: "פסטיבלים" },
      { id: "fair", label: "ירידים" },
      { id: "live_show", label: "הופעות חיות" },
      { id: "street_performance", label: "מופעי רחוב" },
      { id: "food_festival", label: "פסטיבלי אוכל" },
      { id: "wine_beer_festival", label: "פסטיבלי יין ובירה" },
      { id: "culture_event", label: "אירועי תרבות" },
      { id: "sports_event", label: "אירועי ספורט" },
      { id: "night_market", label: "שווקי לילה" },
      { id: "seasonal_event", label: "אירועים עונתיים" },
      { id: "local_celebration", label: "חגיגות מקומיות" },
    ],
  },
  {
    id: "spa_relaxation",
    label: "ספא ורוגע",
    emoji: "🧖",
    subTags: [
      { id: "spa_complex", label: "מתחמי ספא" },
      { id: "massage", label: "עיסויים" },
      { id: "hammam", label: "חמאם" },
      { id: "sauna", label: "סאונה" },
      { id: "bathhouse", label: "מרחצאות" },
      { id: "hot_spring", label: "מעיינות חמים" },
      { id: "thermal_pool", label: "בריכות תרמיות" },
      { id: "wellness_complex", label: "מתחמי Wellness" },
      { id: "relaxation_complex", label: "מתחמי רוגע" },
      { id: "nature_yoga", label: "יוגה בטבע" },
      { id: "meditation", label: "מדיטציה" },
      { id: "retreat", label: "ריטריטים" },
    ],
  },
];

/** 16 סוגי המזון, לבחירה מרובה במסעדות/בתי קפה. */
export const CUISINE_TAGS: TaxonomyOption[] = [
  { id: "italian", label: "🇮🇹 איטלקי" },
  { id: "asian", label: "🥢 אסייתי" },
  { id: "meat_grill", label: "🥩 בשרים ועל האש" },
  { id: "burger", label: "🍔 המבורגר" },
  { id: "mexican", label: "🇲🇽 מקסיקני" },
  { id: "greek", label: "🇬🇷 יווני" },
  { id: "french_bistro", label: "🇫🇷 ביסטרו צרפתי" },
  { id: "indian", label: "🇮🇳 הודי" },
  { id: "mediterranean", label: "🌿 ים־תיכוני" },
  { id: "seafood", label: "🐟 דגים ופירות ים" },
  { id: "pizza", label: "🍕 פיצה" },
  { id: "israeli_middle_eastern", label: "🥙 ישראלי ומזרח תיכוני" },
  { id: "breakfast_brunch", label: "🥐 ארוחת בוקר ובראנץ'" },
  { id: "cafe", label: "☕ בית קפה" },
  { id: "desserts", label: "🍰 קינוחים ומתוקים" },
  { id: "salads_healthy", label: "🥗 סלטים ובריאות" },
];

export const SEASON_OPTIONS: TaxonomyOption[] = [
  { id: "spring", label: "אביב" },
  { id: "summer", label: "קיץ" },
  { id: "autumn", label: "סתיו" },
  { id: "winter", label: "חורף" },
  { id: "all_year", label: "כל השנה" },
];

export const CHILD_AGE_OPTIONS: TaxonomyOption[] = [
  { id: "0-3", label: "0-3" },
  { id: "3-7", label: "3-7" },
  { id: "7-12", label: "7-12" },
  { id: "12-18", label: "12-18" },
];

export const BUDGET_TIER_OPTIONS: TaxonomyOption[] = [
  { id: "$", label: "$" },
  { id: "$$", label: "$$" },
  { id: "$$$", label: "$$$" },
  { id: "$$$$", label: "$$$$" },
];